builds:
- env:
  - CGO_ENABLED=1
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: dutchakdev
    name: clif
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}"